sudo: required
language: android
jdk: oraclejdk8
env:
  global:
   # install timeout in 3 minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=3
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=27.0.3
android:
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
  components:
      - tools
      - platform-tools
      # The BuildTools version used by your project
      - build-tools-$ANDROID_BUILD_TOOLS_VERSION
      # The SDK version used to compile your project
      - android-$ANDROID_API_LEVEL
script:
    - chmod +x ./gradlew