package com.adoranwodo.gottrivia.database

import com.adoranwodo.gottrivia.model.Question

const val DATABASE_NAME = "GotTriviaQuiz.db"

const val QUESTION_TABLE_NAME = "questions"
const val SCORE_TABLE_NAME = "scores"

const val easy = "Easy"
const val medium = "Medium"
const val hard = "Hard"

const val funeralPyre = "Funeral pyre"

val appQuestions = arrayListOf<Question>(
    Question( question = "Daenerys Targaryen hatched her dragon eggs in a ", difficulty = easy, optionA = "Fireplace",
        optionB = funeralPyre, optionC = "Burning forest", answer = funeralPyre),
    Question(question = "Valar Morghulis is usually responded with ", difficulty = hard, optionA = "Valar Bohnaris",
        optionB = "Valar Rohaires", optionC = "Valar Dohaeris", answer = "Valar Dohaeris"),
    Question(question = "What can put out wildfire", difficulty = hard, optionA = "Sand",
        optionB = "Water", optionC = "Dragon's blood", answer = "Sand"),
    Question(question = "What substance is capable of defeating whitewalkers", difficulty = easy, optionA = "Dragon Stone",
        optionB = "Valyrian Steel", optionC = "Wildfire", answer = "Valyrian Steel"),
    Question(question = "How many times has Beric Dondarrion been brought back to life", difficulty = hard, optionA = "Five",
        optionB = "Seven", optionC = "Six", answer = "Six"),
    Question(question = "Which Stark family direwolf was killed in retaliation for an attack on Price Joffery", difficulty = medium,
        optionA = "Lady", optionB = "Nymeria", optionC = "Ghost", answer = "Lady"),
    Question(question = "Arya's punishment for stealing from the many-face god was", difficulty = easy,
        optionA = "Losing Needle", optionB = "Hunger", optionC = "Blindness", answer = "Blindness"),
    Question(question = "This character said 'Its nothing' right before he died", difficulty = hard,
        optionA = "Tywin Lannister", optionB = "King Joffrey", optionC = "Renly Baratheon", answer = "King Joffrey"),
    Question(question = "The name of King Tommen's favorite cat is", difficulty = medium,
        optionA = "Battle Pus", optionB = "Little Lion", optionC = "Ser Pounce", answer = "Ser Pounce"),
    Question(question = "What's the name of Ned Stark's greatsword", difficulty = medium,
        optionA = "Ice", optionB = "Northguard", optionC = "Widow's Wall", answer = "Ice"),
    Question(question = "Who shoots the flaming arrow that destroy's Stannis fleet in Blackwater Bay", difficulty = hard,
        optionA = "King Joffrey", optionB = "Jaime Lannister", optionC = "Bronn", answer = "Bronn"),
    Question(question = "Prince Oberyn Martell is nicknamed the Red Viper because of his combat and ", difficulty = medium,
        optionA = "Killings", optionB = "Ruby colored armor", optionC = "Knowledge of poisons", answer = "Knowledge of poisons"),
    Question(question = "The Night King was created using a dagger made of ", difficulty = easy,
        optionA = "Blue Ice", optionB = "Dragonglass", optionC = "Valyrian Steel", answer = "Dragonglass"),
    Question(question = "How many arrows does Ramsay Bolton let loose at Rickon Stark ", difficulty = medium,
        optionA = "Two", optionB = "Three", optionC = "Four", answer = "Four"),
    Question(question = "Who created the secret tunnel in the sewers under Casterly Rock ", difficulty = hard,
        optionA = "Varys", optionB = "Tyrion Lannister", optionC = "Lord Baelish", answer = "Tyrion Lannister"),
    Question(question = "What's Sansa Stark's favorite thing to eat ", difficulty = easy,
        optionA = "Honey cake", optionB = "Strawberry pie", optionC = "Lemon cake", answer = "Lemon cake"),
    Question(question = "Dead creatures revived by white walkers are known as ", difficulty = easy,
        optionA = "Walkers", optionB = "Wights", optionC = "Dead", answer = "Wights"),
    Question(question = "Who was Lord Commander of the Kingsguard at the beginning of Game of Thrones ", difficulty = easy,
        optionA = "Ser Jaime Lannister", optionB = "Ser Jeor Mormont", optionC = "Ser Barristan Selmy", answer = "Ser Barristan Selmy"),
    Question(question = "Who was Margaery Tyrell's first husband ", difficulty = easy,
        optionA = "Renly Baratheon", optionB = "Tommen Baratheon", optionC = "Joffrey Baratheon", answer = "Renly Baratheon"),
    Question(question = "How many times has Sansa Stark been married", difficulty = easy,
        optionA = "Once", optionB = "Twice", optionC = "Three times", answer = "Twice"),
    Question(question = "Who is the ruler of the Iron Islands at the beginning of Game of Thrones", difficulty = easy,
        optionA = "Yara Greyjoy", optionB = "Aeron Greyjoy", optionC = "Balon Greyjoy", answer = "Balon Greyjoy"),
    Question(question = "Who is the mad king's first born son", difficulty = easy,
        optionA = "Rhaegal Targaryen", optionB = "Rhaegar Targaryen", optionC = "Viserys Targaryen", answer = "Rhaegar Targaryen"),
    Question(question = "Who delivered the fatal blow to Robb Stark", difficulty = medium,
        optionA = "Walder Frey", optionB = "Roose Bolton", optionC = "Alliser Thorne", answer = "Roose Bolton"),
    Question(question = "Grey Worm and Missandei became allies of Daenaerys Targaryen after she liberated the slaves of which city", difficulty = easy,
        optionA = "Yunkai", optionB = "Astapor", optionC = "Meeren", answer = "Astapor"),
    Question(question = "What is the name of the royal executioner who beheaded Ned Stark", difficulty = medium,
        optionA = "Ser Janos Trant", optionB = "Ser Meryn Trant", optionC = "Ser Ilyn Payne", answer = "Ser Ilyn Payne"),
    Question(question = "Which rival king attempted to take King's Landing during the Battle of the Blackwater", difficulty = medium,
        optionA = "Balon Greyjoy", optionB = "Stannis Baratheon", optionC = "Renly Baratheon", answer = "Stannis Baratheon"),
    Question(question = "Who was the fool that helped Sansa Stark escape King's Landing after Joffrey's death", difficulty = hard,
        optionA = "Vardis Egen", optionB = "Dontos Hollard", optionC = "Eddison Tollett", answer = "Dontos Hollard"),
    Question(question = "The father of Gilly's son is ", difficulty = easy,
        optionA = "Samwell Tarly", optionB = "Craster", optionC = "Tormund Giantsbane", answer = "Craster"),
    Question(question = "Where does Arya Stark train to become a faceless man", difficulty = easy,
        optionA = "Meereen", optionB = "Pentos", optionC = "Braavos", answer = "Braavos"),
    Question(question = "Thoros of Myr is responsible for reviving which character from the dead", difficulty = hard,
        optionA = "Sandor Clegane", optionB = "Gregor Clegane", optionC = "Beric Dondarrion", answer = "Beric Dondarrion"),
    Question(question = "Davos Seaworth grew up in the slums of which city", difficulty = easy,
        optionA = "Dorne", optionB = "King's landing", optionC = "Astapor", answer = "King's landing"),
    Question(question = "Who is Lyanna to Jorah Mormont", difficulty = easy,
        optionA = "Daughter", optionB = "Sister", optionC = "Cousin", answer = "Cousin"),
    Question(question = "What is the surname given to the bastards born in Dorne", difficulty = easy,
        optionA = "Stone", optionB = "Sand", optionC = "Storm", answer = "Sand"),
    Question(question = "The Mountain is the nickname for which character", difficulty = easy,
        optionA = "Geroid Clegane", optionB = "Sandor Clegane", optionC = "Gregor Clegane", answer = "Gregor Clegane"),
    Question(question = "Who is not on Arya Starks list", difficulty = easy,
        optionA = "Meryn Trant", optionB = "Rorge", optionC = "Tommen Baratheon", answer = "Tommen Baratheon"),
    Question(question = "Who is known as 'The-King-Beyond-the-Wall' ", difficulty = medium,
        optionA = "Stannis Baratheon", optionB = "Mance Rayder", optionC = "Tormund Giantsbane", answer = "Mance Rayder"),
    Question(question = "Who is the ruler of the Iron Islands at the beginning of Game of Thrones ", difficulty = easy,
        optionA = "Yara Greyjoy", optionB = "Aeron Greyjoy", optionC = "Balon Greyjoy", answer = "Balon Greyjoy"),
    Question(question = "Which city did Samwell Tarly travel to in order to train as a maester ", difficulty = medium,
        optionA = "High Garden", optionB = "Oldtown", optionC = "Gulltown", answer = "Oldtown"),
    Question(question = "Who does Tywin plan to re-marry his daughter Cersie to", difficulty = hard,
        optionA = "Euron Greyjoy", optionB = "Oberyn Martell", optionC = "Loras Tyrell", answer = "Loras Tyrell"),
    Question(question = "Which name is given to the bastards of The Reach", difficulty = medium,
        optionA = "Stone", optionB = "Flowers", optionC = "Bastard", answer = "Flowers"),
    Question(question = "At Hoster Tully's funeral, who shot the burning arrow that hit its mark", difficulty = medium,
        optionA = "Edmure Tully", optionB = "Brynden Tully", optionC = "Lord Karstark", answer = "Brynden Tully"),
    Question(question = "Who was the liege lord of the Freys before the War of the Five Kings", difficulty = medium,
        optionA = "Robert Baratheon", optionB = "Jon Arryn", optionC = "Hoster Tully", answer = "Hoster Tully"),
    Question(question = "What was the name of the boy Arya was playing with (and who later died) when Nymeria attacked Joffrey",
        difficulty = medium, optionA = "Mycah", optionB = "Pyp", optionC = "Gendry", answer = "Pyp"),
    Question(question = "Who is Myrcella betrothed to in season 2", difficulty = medium,
        optionA = "Trystane Martell", optionB = "Sam Crakehall", optionC = "Oberyn Martell", answer = "Trystane Martell"),
    Question(question = "Which of these is not a direwolf", difficulty = medium,
        optionA = "Nymeria", optionB = "Storm", optionC = "Summer", answer = "Storm"),
    Question(question = "What are the words of House Martell", difficulty = medium, optionA = "Growing Strong",
        optionB = "Hear Me Roar", optionC = "Unbowed, Unbent, Unbroken", answer = "Unbowed, Unbent, Unbroken"),
    Question(question = "How many Starks appeared in the first episode of the series", difficulty = medium,
        optionA = "7", optionB = "8", optionC = "9", answer = "8"),
    Question(question = "How many kings did Tywin Lannister serve as the Hand", difficulty = medium,
        optionA = "1", optionB = "2", optionC = "3", answer = "3"),
    Question(question = "Which of the following characters appears in season 1", difficulty = medium,
        optionA = "Stannis Baratheon ", optionB = "Beric Dondarrion", optionC = "Roose Bolton", answer = "Beric Dondarrion"),
    Question(question = "Which of the following types of wine does the wine merchant attempt to poison Daenerys with", difficulty = hard,
        optionA = "Arbor Red", optionB = "Dornish Red", optionC = "Stormland Red", answer = "Arbor Red"),
    Question(question = "What is the first thing Jon Snow says in the first episode in season 4", difficulty = hard,
        optionA = "I can't believe Robb is dead", optionB = "The Halfhand believed our only chance to stop Mance was to get a man inside his army", optionC = "Last time I saw him, he was in the courtyard at Winterfell", answer = "Last time I saw him, he was in the courtyard at Winterfell"),
    Question(question = "Brienne pledged her alliance to which of these pairs", difficulty = hard, optionA = "Sansa Stark and Selwyn Tarth",
        optionB = "Catelyn Stark and Renly Baratheon", optionC = "Stannis Baratheon and Catelyn Stark", answer = "Catelyn Stark and Renly Baratheon"),
    Question(question = "What is Meera's relationship to Howland Reed", difficulty = hard, optionA = "daughter",
        optionB = "aunt", optionC = "cousin", answer = "daughter"),
    Question(question = "During the Red Wedding, which Houses were allies against the Starks", difficulty = hard, optionA = "Frey, Lannister and Tully",
        optionB = "Frey, Forrester and Lannister", optionC = "Frey, Bolton and Lannister", answer = "Frey, Bolton and Lannister"),
    Question(question = "Which House is extinct at the time Cersei Lannister becomes Queen of Westeros", difficulty = hard, optionA = "Arryn",
        optionB = "Baratheon", optionC = "Greyjoy", answer = "Baratheon"),
    Question(question = "Who was Ros' regular customer at Winterfell", difficulty = hard, optionA = "Theon Greyjoy",
        optionB = "Tywin Lannister", optionC = "Randyll Tarly", answer = "Theon Greyjoy"),
    Question(question = "Which kings did Jaime Lannister serve as a Kingsguard", difficulty = hard, optionA = "Robert Baratheon, Joffrey Baratheon and Aerys I",
        optionB = "Maekar I, Robert Baratheon and Joffrey Baratheon", optionC = "Aerys II, Robert Baratheon and Joffrey Baratheon ", answer = "Aerys II, Robert Baratheon and Joffrey Baratheon "),
    Question(question = "What is Visenya Targaryen's relationship to Aegon I", difficulty = hard, optionA = "Wife and sister",
        optionB = "Wife and aunt", optionC = "Wife and cousin", answer = "Wife and sister"),
    Question(question = "Arthur Dayne was a member of the Kingsguard of which king", difficulty = hard, optionA = "Aerys I",
        optionB = "Aerys II", optionC = "Aegon I", answer = "Aerys II"),
    Question(question = "What does Daenerys mean when she says 'Shekh ma sheieraki anni' ", difficulty = hard, optionA = "Moon of my life",
        optionB = "Sun of my life", optionC = "My sun and stars", answer = "My sun and stars")
)